name: Buiild

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  build_binary:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - { target: aarch64-unknown-linux-gnu , use-cross: true, name: kotka-linux-aarch64 }
          - { target: i686-unknown-linux-gnu , use-cross: true, name: kotka-linux-i686 }
          - { target: x86_64-pc-windows-gnu , use-cross: true, name: kotka-windows }
          - { target: aarch64-linux-android, use-cross: true, name: kotka-android }
          - { target: x86_64-unknown-linux-gnu, name: kotka-linux }
    steps:
      - uses: actions/checkout@v3
      - name: Extract crate information
        shell: bash
        run: |
          echo "PROJECT_NAME=$(sed -n 's/^name = "\(.*\)"/\1/p' Cargo.toml | head -n1)" >> "$GITHUB_ENV"
          echo "PROJECT_VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -n1)" >> "$GITHUB_ENV"

      - run: rustup component add clippy
      - name: Run Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          use-cross: ${{ matrix.arch.use-cross }}


      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.arch.use-cross }}
          command: build
          args: --release --target=${{ matrix.arch.target }}

      - name: Copy non-Windows binary
        shell: bash
        if: ${{ matrix.arch.target != 'x86_64-pc-windows-gnu' }}
        run: |
          cp  target/${{ matrix.arch.target }}/release/${{ env.PROJECT_NAME }} ${{ matrix.arch.name }}

      - name: Copy Windows binary
        shell: bash
        if: ${{ matrix.arch.target == 'x86_64-pc-windows-gnu' }}
        run: |
            cp  target/${{ matrix.arch.target }}/release/${{ env.PROJECT_NAME }}.exe ${{ matrix.arch.name }}.exe

      - name: Upload non-Windows package artifact
        uses: actions/upload-artifact@v3
        if: ${{ matrix.arch.target != 'x86_64-pc-windows-gnu' }}
        with:
          path: ${{ matrix.arch.name }}

      - name: Upload Windows package artifact
        uses: actions/upload-artifact@v3
        if: ${{ matrix.arch.target == 'x86_64-pc-windows-gnu' }}
        with:
          path: ${{ matrix.arch.name }}.exe

  build_macos_binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract crate information
        shell: bash
        run: |
            echo "PROJECT_NAME=$(sed -n 's/^name = "\(.*\)"/\1/p' Cargo.toml | head -n1)" >> "$GITHUB_ENV"
            echo "PROJECT_VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -n1)" >> "$GITHUB_ENV"

      - name: Build
        uses: actions-rs/cargo@v1
        with:
            command: build
            args: --release

      - name: Copy
        shell: bash
        run: |
          cp  target/release/${{ env.PROJECT_NAME }} ${{ env.PROJECT_NAME }}-macos

      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.PROJECT_NAME }}-macos


  release:
    needs: [build_binary, build_macos_binary]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            view the CHANGELOG.md for full changes
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
